### ISSUE TITLE
Action not working properly inside example/

### ISSUE THREAD

**Issue by llucax** [zgosalvez/github-actions-analyze-dart#2]
Hi, I have a package that provides an `example`. When running `flutter analyze` locally, it all works fine, but when running this GitHub action I get some errors. See: https://github.com/lunofono/lunofono_player/pull/9/checks?check_run_id=1727456103#step:6:18

At some point I had those errors locally, but it was fixed after doing a `flutter pub get`, so maybe the action is missing that step?

**Comment by llucax** [comment]
> At some point I had those errors locally, but it was fixed after doing a `flutter pub get`, so maybe the action is missing that step?

The weird thing about this is none of the `pubspec.lock` files were changed (in the root or in the `example/`) by the `pub get`.

**Comment by zgosalvez** [comment]
@llucax, I'll check this out further tomorrow. The readme already shows examples to run `flutter pub get` or `dart pub get`, or did you mean it also needs to be run inside of your `examples` folder?

**Comment by llucax** [comment]
> @llucax, I'll check this out further tomorrow. The readme already shows examples to run `flutter pub get` or `dart pub get`, or did you mean it also needs to be run inside of your `examples` folder?

Yes, I'm running `flutter pub get` in the top folder. Not sure if it is necessary to run it somewhere else (it is supposed to run inside `example` too automatically when doing it in the top-level). I'm not exactly sure why this is failing in the action and not locally, nor how could I reproduce it locally, so I'm sorry I can give so few details. I can't spend much time on debugging this myself now, but maybe you had an idea on what the cause could be. If I manage to do some more investigation I will share my findings here.

**Comment by zgosalvez** [comment]
> See: https://github.com/lunofono/lunofono_player/pull/9/checks?check_run_id=1727456103#step:6:18

@llucax, this link no longer points to the issue. Please identify which run failed here: https://github.com/lunofono/lunofono_player/actions. I want to be sure of the error first before I attempt to debug.

**Comment by llucax** [comment]
I created a separate PR that only upgrades to this action, so it's easier to see the issue in isolation: https://github.com/lunofono/lunofono_player/pull/12

**Comment by zgosalvez** [comment]
Great! I appreciate the help. I'll look into this in the coming days.

**Comment by llucax** [comment]
The job using the action is `test (static)`, here is a direct link to the failure again: https://github.com/lunofono/lunofono_player/pull/12/checks?check_run_id=1730340592#step:6:14

**Comment by zgosalvez** [comment]
@llucax, I found that the issue is caused by the `dartanalyzer` running from the top-level project, since it is also analyzing the `example` directory, which is technically a different project. I got it to work by splitting the jobs like so:
```yaml
    - name: Analyze lib
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        working-directory: lib
        fail-on-warnings: true

    - name: Analyze test
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        working-directory: test
        fail-on-warnings: true

    - name: Analyze example
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        working-directory: example
        fail-on-warnings: true
```
I could also implement an `excludes` input to this action so that we can simplify the workflow further like so:
```yaml
- name: Analyze
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        excludes: example
        fail-on-warnings: true

    - name: Analyze example
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        working-directory: example
        fail-on-warnings: true
```
Thoughts?
