### ISSUE TITLE
Annotations section not populated with anything

### ISSUE THREAD

**Issue by Bhupesh-V** [zgosalvez/github-actions-analyze-dart#8]
I have the following config
```yaml
on: push

name: Static Analysis

jobs:
  build:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - name: Setup dependencies
        run: flutter pub get
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v1
        with:
          fail-on-warnings: true
```

I can see that the warnings are successfully printed in the logs but the annotation section gives this error

<img width="925" alt="Screenshot 2021-11-08 at 2 07 47 PM" src="https://user-images.githubusercontent.com/34342551/140710331-dedc4f8b-d04f-474d-b533-ea1bc97c537d.png">
